# https://pages.github.com/versions/
# https://jekyllrb.com/docs/continuous-integration/

language: ruby
rvm:
  - 2.1

git:
  depth: 8

bundler_args: --without benchmark:site:development
cache: bundler
sudo: false

before_install:
  # Was: - nvm install v4.4
  - nvm install v8.1
  #- npm i npm -g
  - npm -v

install:
  - bundle install
  #- gem install github-pages
  - npm install

script:
  - npm test
  - npm run build
  # http://localhost:4000
  # http://cruft.io/posts/automated-accessibility-testing-node-travis-ci-pa11y/
  # Sleep while Github-Pages re-builds ... ?
  - sleep 40; npm run pa11y-ci

after_script:
  - npm run count
  - npm run version

notifications:
  webhooks:
    #- http://iet-embed-acct.open.ac.uk/dev/travis-hook/

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# End.
