# https://pages.github.com/versions/
# https://docs.travis-ci.com/user/languages/ruby
# https://github.com/jekyll/jekyll
# https://jekyllrb.com/docs/continuous-integration/

language: ruby
rvm:
  - 2.1

git:
  depth: 8

bundler_args: --without benchmark:site:development
cache: bundler
sudo: false

before_script:
  #- bundle install
  #- gem install github-pages
  - make npm-install

script:
  - jekyll --version
  - grunt
  # Was: - bundle exec jekyll build
  - jekyll build
  # http://localhost:4000

after_script:
  - grunt exec:count

notifications:
  webhooks:
    #- http://iet-embed-acct.open.ac.uk/dev/travis-hook/

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

#End.
