# Site settings
title: Nick Freear’s blog
email: nfreear+@+yahoo.co.uk
description: Accessibility, e-learning, internationalization, web dev, Moodle and other stuff
ex_long_desc: > # this means to ignore newlines until "baseurl:"
  This is an experiment!
  I’m rebooting my blog using GitHub pages & Jekyll.
  <a href="https://github.com/nfreear/nfreear.github.io">(source)</a>
  <br>
  The blog archive is at <a href="http://freear.org.uk">Freear.org.uk</a> &bull; &copy;Nick Freear.

  <i>
  <a href="http://nfreear.mit-license.org/"><img alt="MIT license"
  src="/assets/shields-io-license-MIT.svg"
  data-src="https://img.shields.io/badge/license-MIT-blue.svg" title=
  "Code: source code snippets are released under an MIT license"></a>

  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"
  ><img alt="Creative Commons License"
  src="https://licensebuttons.net/l/by-sa/4.0/88x31.png" title=
  "Content: released under a Creative Commons Attribution-ShareAlike 4.0 License"></a>
  </i>
excerpt_separator: "<!--more-->"
#paginate: 2
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nick.freear.org.uk"
#url: "http://nfreear.github.io" # the base hostname & protocol for your site
twitter_username: nfreear
github_username:  nfreear


# Site setting extensions.

# 'truncatewords: 28' (Was: truncate: 220)
ex_excerpt_truncate: 28
ex_comments: true

js_config:
  # Google Analytics.
  analytics_id: UA-8330079-6
  comment_via: IntenseDebate
  comment_acct: "e7e6973336bc863b96ed224779c2629c"
  comment_div: "x-idc-comments-wrap"
  #"7a9708780eedbfa6976e905b93424255"

# https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#standard-filters [ "%b %-d, %Y"  ]
date_format: "%-d %B %Y"

ex_custom_nav:
  - <a href="http://freear.org.uk/" title="My legacy blog">Freear.org.uk</a>
  #- <a href="#">Test 2</a>

#ex_site_message: Hello world! Just a <a href="#">test</a>!
ex_site_message: >
  Help us fund features – vote for Open Media Player! &nbsp;
  <a href="https://elevator.jisc.ac.uk/e/accessiblebydesign/idea/open-media-player"
  ><img src="https://img.shields.io/badge/Jisc-vote_%E2%9C%93-ff6d00.svg"
  alt="Vote! Jisc" title="Vote for us in the Jisc Accessible by Design challenge" /></a>

# https://access.ecs.soton.ac.uk/ToolBar/
# https://atbar.org/
ex_atbar: false


exclude:
  - Makefile
  - ".htaccess"
  - index.php
  - _out/
  - _bin/


# Build settings
markdown: kramdown
