# Site settings
title: Nick Freear’s blog
email: nfreear+@+yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  This is an experiment!
  I’m rebooting my blog using GitHub pages & Jekyll.
  The blog archive is at <a href="http://freear.org.uk">Freear.org.uk</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nfreear.github.io" # the base hostname & protocol for your site
twitter_username: nfreear
github_username:  nfreear

x_nicks_setting: hello

# Build settings
markdown: kramdown
